### ISSUE TITLE
[Bug]: Unable to catch API RPC errors

### ISSUE THREAD

**Issue by mnikonov** [MetaMask/metamask-sdk#911]
### SDK

Web

### Provide environment information

Windows 11
VS Code
NodeJS v20.14.0
Angular ^18.0.5

### MetaMask SDK Version

^0.26.1"

### MetaMask Mobile app Version

-

### What browser are you using? (if relevant)

Chrome Version 126.0.6478.63 (Official Build) (64-bit)

### Describe the Bug

If on attempt to execute API, provided by MetaMask SDK, execute RPC call that results in error - it would be shown in console but would **not** be thrown as error

 

### Expected Behavior

It is possible to catch errors for future handling using 

```
try{
}
catch (err:any){
}
```

### To Reproduce

Attemp to execute below code **without** entering password in Metamask

```
var mmSDK = new MetaMaskSDK({...}); 
await mmSDK.init();
var provider = mmSDK.getProvider();

try{
	var accounts = await this.provider.request<string[]>({ method: "eth_requestAccounts" });
}
catch (err:any){
	console.error(err);
}
```

It will be resulted in successful code execution with setting accounts to 'undefined', but, **without catching any errors**. 

In console would be written an error

```
MetaMask - RPC Error: Already processing eth_requestAccounts. Please wait. {code: -32002, message: 'Already processing eth_requestAccounts. Please wait.', stack: '{
  "code": -32002,
  "message": "Already pro…aoehlefnkodbefgpgknn/background-4.js:3:49747)'}
```

**Comment by tovi-fhe** [comment]
I think that I have the same issue.
How can I access the "real" message?
![image](https://github.com/MetaMask/metamask-sdk/assets/160392690/62cdfa25-3abb-4358-998b-1b9460a4d0bd)

catch doesn't catch it.

**Comment by christopherferreira9** [comment]
> I think that I have the same issue. How can I access the "real" message? ![image](https://private-user-images.githubusercontent.com/160392690/342824120-62cdfa25-3abb-4358-998b-1b9460a4d0bd.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTkzMzQzOTMsIm5iZiI6MTcxOTMzNDA5MywicGF0aCI6Ii8xNjAzOTI2OTAvMzQyODI0MTIwLTYyY2RmYTI1LTNhYmItNDM1OC05OThiLTFiOTQ2MGE0ZDBiZC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNjI1JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDYyNVQxNjQ4MTNaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT03NDFhNDljNDU4MjA3MDIyOGYxYmZkYmQwZTczOTk0MGYyMjMxYmMzMmJkNGRkMjQ4NDFhYTk2NjQ3NWU2ODMzJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.DYo1cCeIT4Y0TePBtD1v15fVf2l86MmBU6RAFB7Nl6A)
> 
> catch doesn't catch it.

Hi @tovi-fhe Can you please provide an example we can use to try to reproduce this on our side?

**Comment by christopherferreira9** [comment]
hi @mnikonov ! 
I'm not sure I have understood the issue you're experiencing. 
To get it into the catch block you can simply deny the connection request on MetaMask. Can you please try to catch the exception with this? Keep in mind you'll need to provide a button or some sort of trigger to get it going.

``` javascript
var mmSDK = new MetaMaskSDK({...}); 

 const connect = async () => {
    try {
      await mmSDK?.connect();
    } catch (err) {
      console.log(`err -> `, err);
    }
  };
```

One thing I've noticed is that denying the connection will only return the error code in the `err` object instead of the full object. Will check internally if this is something we can return with it. It is currently returning error code `4001` which means the [user rejected the request](https://docs.metamask.io/wallet/reference/provider-api/#errors).

**Comment by mnikonov** [comment]
I'm never getting inside catch block if RPC request finishing with error.

**Comment by christopherferreira9** [comment]
> I'm never getting inside catch block if any RPC request finishing with error. SDK writes such issues to console log, but, not throwing them. You can try to reproduce this issue by calling any async API from SDK that performs RPC request

I'm having issues reproducing what you mention.


https://github.com/MetaMask/metamask-sdk/assets/104831203/d1d31577-4f1f-4d53-b094-40c1958d70f3

**Comment by tovi-fhe** [comment]
The issue is, if you have this modifier for example:
```
    modifier onlyAdmin() {
        require(msg.sender == admin, "Not an admin");
        _;
    }
```

When you call the contract (wrapped with try & catch block) and it throws this exception, you will enter the catch block, but the error variable won't contain the message from the contract (for that case the "Not an admin" message).
But you can see it in the console.

**Comment by mnikonov** [comment]
@christopherferreira9 Please find angular test project [metamask-trycatch-angular.zip](https://github.com/user-attachments/files/15980973/metamask-trycatch-angular.zip)

This project contains next piece of code 

```typescript
try{
    await provider?.request({
       method: "wallet_switchEthereumChain",
        params: [{ chainId: '0x' + networkInfo.chainId.toString(16) }],
    });
}
catch (err: any){
    if (err.code === 4902) {
        console.log("Chain not added : " + err.message);
        ....
    }
}
```
that should write message to browser console

Steps to reproduce

1. Unzip project
2. Install node.js, if it's not installed
3. Install project dependencies with command 'npm install'
4. Run project with command 'npm run start' or press F5 in Visual Studio Code
5. Login in MetaMask
6. Press 'test' button
7. Open browser logs

Actual result

<img width="418" alt="console-log" src="https://github.com/MetaMask/metamask-sdk/assets/10001265/d4bd8ba3-093e-4174-9929-ddc015a2c5f7">

In console log presen only exception from SDK and there is no message that begins with **'Chain not added...'**

**Comment by christopherferreira9** [comment]
Thank you for the example, it helped a lot!  Just realised the issue is related to extension and I wrongly assumed it was mobile related. We're going to see what we can do about it. Thank you for reporting!

**Comment by omridan159** [comment]
Hi @mnikonov,

We have addressed the issue you reported in this PR [MetaMask SDK PR #917](https://github.com/MetaMask/metamask-sdk/pull/917)

The fix will be included in the next SDK release.

Thank you for your patience and for providing the detailed reproduction steps!

**Comment by mnikonov** [comment]
@omridan159 In metamask/sdk мукышщт 0.26.4 кудуфыу this issue still reproducing

**Comment by andremfaria** [comment]
Hello,
I'm experiencing the same issue. Based on my testing, the problem started with @metamask/sdk-react version 0.20.5. I tested version 0.26.4, and the issue persists.

**Comment by andremfaria** [comment]
Hello @omridan159 ,
I'm experiencing the same issue. Based on my testing, the problem started with @metamask/sdk-react version 0.20.5. I tested version 0.26.4, and the issue persists.

**Comment by christopherferreira9** [comment]
Reopening this issue for further investigation.

**Comment by christopherferreira9** [comment]
Hi @mnikonov . I'm still struggling to reproduce. The only part I was able to reproduce was the denial of the connection itself and I'm raising that internally to get fixed.
As for the switchChain example you provided I wasn't able to reproduce it. Can you please check if I'm following the flow you're expecting?

https://github.com/MetaMask/metamask-sdk/assets/104831203/ff4112ed-fc0c-4ba6-a6de-97ecc8c0b1b9

**Comment by christopherferreira9** [comment]
> Hello @omridan159 , I'm experiencing the same issue. Based on my testing, the problem started with @metamask/sdk-react version 0.20.5. I tested version 0.26.4, and the issue persists.

Are you able to share an example where you see this happening @andremfaria ?

**Comment by andremfaria** [comment]
Hi @christopherferreira9,

I'm able to reproduce the issue with this mini example: [https://github.com/andremfaria/mm-cannot-catch-exception](https://github.com/andremfaria/mm-cannot-catch-exception).

In my scenario, I cannot catch the error when the user cancels an ERC-20 approve transaction.

However, if I change the `sdk-react` version to 0.20.4, it works as expected.

**Comment by christopherferreira9** [comment]
@andremfaria Something is not adding up. Can you please check the MetaMask extension you currently have installed? Wasn't able to reproduce using extension `11.16.14` and `11.16.15` + sdk-react `0.26.4`.

https://github.com/MetaMask/metamask-sdk/assets/104831203/c4be1df3-9438-4e77-9812-128bba4897f0

**Comment by andremfaria** [comment]
@christopherferreira9 I retested the issue and can confirm that version `0.26.4` has fixed the problem in my scenario.
Thank you!

**Comment by christopherferreira9** [comment]
Awesome @andremfaria ! I'm gonna close this issue for now. Thank you for your assistance!

**Comment by andremfaria** [comment]
@christopherferreira9 Not sure, but maybe I'm facing a variant or related issue.

When you click "Connect" in the MetaMask modal, I'm unable to catch the user-rejected error. However, if you try to connect again, MetaMask will prompt immediately, and if you cancel, it will correctly catch the error and display a "failed to connect" message on the console.

You can see this behaviour in the attached video. Is this behaviour expected? Is there any way I can catch the first rejection?

I'm using the CRA example app. https://github.com/MetaMask/metamask-sdk/tree/main/packages/examples/create-react-app

https://github.com/user-attachments/assets/91d0fd6b-c400-4134-bcfb-7eb91a55ea42
